name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: ${{matrix.symfony-require}}
      SYMFONY_DEPRECATIONS_HELPER: weak

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.1
          - 8.2
        dependencies:
          - highest
        stability:
          - stable
        symfony-require:
          - ""
        include:
          # Tests the lowest set of dependencies
          - dependencies: lowest
            stability: stable
            php-version: 8.1
            symfony-require: 5.4.*

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install PHP with PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          ini-values: date.timezone=UTC,memory_limit=-1,default_socket_timeout=10,session.gc_probability=0,apc.enable_cli=1,zend.assertions=1
          extensions: redis,apcu
          tools: composer:v2,flex

      - name: Enforce using stable dependencies
        run: composer config minimum-stability stable
        if: ${{ matrix.stability == 'stable' }}

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist --optimize-autoloader

      - name: Run PHPUnit
        run: composer test
